# -*- coding: utf-8 -*-
"""KNN-SIMDATA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkeTKSgbRScJY4upGmW7jtJjiw5IF_QW

# KNN WITH SIMULATED DATA
# KNN COM DADOS SIMULADOS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import pandas as pd

data = {
    'signal_strength': [2.5, 1.0, 4.8, 0.8, 3.2, 1.5, 3.5, 0.5, 2.0, 1.2, 2.8, 4.2, 3.0],
    'interference': [0.5, 2.5, 1.0, 3.5, 1.8, 2.8, 1.2, 4.0, 0.8, 2.0, 3.0, 0.5, 1.5],
    'received': [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1]
}

df = pd.DataFrame(data)
df.head(5)

data_pred = {
    'signal_strength': [1.0, 3.0, 0.8, 4.5, 2.2],
    'interference': [2.0, 0.5, 4.0, 1.2, 3.5]
}

df_pred = pd.DataFrame(data_pred)
df_pred.head(5)

ax = plt.subplot()
colors = ['red' if category == 0 else 'green' for category in df['received']]
ax.scatter(df['signal_strength'], df['interference'], c=colors)
plt.show()

ax = plt.subplot()
colors = ['red' if category == 0 else 'green' for category in df['received']]
ax.scatter(df['signal_strength'], df['interference'], c=colors)
ax.scatter(df_pred['signal_strength'], df_pred['interference'], c='blue', marker='s')
plt.show()

x = df[['signal_strength', 'interference']]
y = df['received']

x_pred = df_pred[['signal_strength', 'interference']]

classifier0 = KNeighborsClassifier(n_neighbors=3)
classifier0.fit(x, y)

y_pred0 = classifier0.predict(x_pred)

ax = plt.subplot()
colors = ['red' if category == 0 else 'green' for category in df['received']]
ax.scatter(df['signal_strength'], df['interference'], c=colors)


ax.scatter(df_pred['signal_strength'], df_pred['interference'], c=y_pred0, marker='s')
plt.show()